name: Call Terraform Module Workflow

on:
  workflow_dispatch: # Trigger manually
  push:
    branches:
      - main
      - feature1

jobs:
  call-terraform-module:
    name: Call Reusable Terraform Workflow
    uses: Digidense/infra_module_repo/.github/workflows/terraform-pipeline.yml@main
    with:
      aws_region: 'us-east-1' # Update with your region
      branch_name: 'feature1' # Update with the branch for Terraform apply
    secrets: inherit
